### ISSUE TITLE
Error when calling the service climate/set_temperature. unknown error

### ISSUE THREAD

**Issue by Sputnikchen** [tetele/hvac_group#91]
### System Health details

Version: core-2024.3.1
Python-Version: 3.12.2
OSVersion: 6.1.73-haos-raspi

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/tetele/hvac_group/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Can't set anything. Error setting temp and error setting HVAC-mode (climate/set_hvac_mode. unknown error)

### Reproduction steps

1. Install HVAC group
2. Create group with 3 TRV
3. Open group and try to change temp or hvac-mode

### Debug logs

```text
Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:239
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 07:07:23 (5 Vorkommnisse)
Zuletzt protokolliert: 07:14:22

[547274524224]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 864, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/hvac_group/climate.py", line 1039, in async_set_temperature
    await self.async_commit_state_if_running(update_actuators=True)
  File "/config/custom_components/hvac_group/climate.py", line 536, in async_commit_state_if_running
    await self.async_run_hvac(update_actuators=update_actuators)
  File "/config/custom_components/hvac_group/climate.py", line 684, in async_run_hvac
    await self.async_control_actuators(
  File "/config/custom_components/hvac_group/climate.py", line 707, in async_control_actuators
    await self._async_turn_on_heaters()
  File "/config/custom_components/hvac_group/climate.py", line 1106, in _async_turn_on_heaters
    await targets.async_turn_on(
  File "/config/custom_components/hvac_group/actuator.py", line 317, in async_turn_on
    await actuator.async_turn_on(
  File "/config/custom_components/hvac_group/actuator.py", line 245, in async_turn_on
    await self.async_set_temperature(
  File "/config/custom_components/hvac_group/actuator.py", line 122, in async_set_temperature
    assert None in (temperature, target_temp_high, target_temp_low)
AssertionError
```

**Comment by Ra72xx** [comment]
I can't set temperatures, too. Any idea? This bug report is pretty long stale...

**Comment by Spiderman124** [comment]
I have exactly the same problem and haven't found a solution yet.
The error message in German language after click up/ down the temperature:
"Die Aktion climate/set_temperature konnte nicht ausgeführt werden. unknown error"

**Comment by Sputnikchen** [comment]
Maybe it must be  
 
 climate.set_temperature 
 
 and not 
 
 climate/set_temperature 
 
 
 
 
 
 
 
 
 I have exactly the same problem and haven't found a solution yet. 
 
The error message in German language after click up/ down the temperature: 
 
"Die Aktion climate/set_temperature konnte nicht ausgeführt werden. unknown error"

**Comment by Spiderman124** [comment]
Thanks Sputnikchen for your answer. 
It works now! The problem must have been between the keyboard and the chair.
